eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8076/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

spring:
  application:
    name: "payment"
